### PR TITLE
ZeroPoke's Plugins FontDeck, RounDeck, ClearDeck

### PR DESCRIPTION
**Pull request by ZeroPoke**
Submitting my Plugins to the repo.

### CODE REVIEW

**Comment by coolavery** [comment]
Hey @ZeroPoke , looks great! I just found one bug during testing, the FontDeck plugin fails to reload [here](https://github.com/ZeroPoke/crankshaft-fontdeck/blob/8863c8f93438dd24d17d664356aaf2f72b7375f9/src/index.ts#L172).

It's kind of an undocumented requirement, but the plugin folder name should match your plugin ID. In this case, the plugin folder is called `crankshaft-fontdeck` (the folder inside the [archive](https://github.com/CrankshaftForSteam/crankshaft-plugins/pull/10/files#diff-18d7f9b905f83805c42db6d239a7fb0207d4b32193202eb13ba077caed424c3cR122)), but you're reloading with the plugin ID `fontdeck`. Renaming the plugin folder to `fontdeck` fixes it for me (or you can use `crankshaft-fontdeck` when reloading, whatever you prefer).

Edit: Just to add, there's no easy way to test installing from an archive right now, but I tested this by downloading the archive and extracting it into `~/.var/app/space.crankshaft.Crankshaft/data/crankshaft/plugins`.

**Comment by ZeroPoke** [comment]
And the worst part of that is Drakia warned me and I forgot.

I believe it should be better.

**Comment by coolavery** [comment]
Ah sorry one more thing, after updating the versions to 1.0.1, the version in the plugin.toml for the three plugins is still 1.0.0.

Sorry I know it's bad that there's duplicate stuff in `plugins.json` and `plugin.toml`'s, it's for legacy reasons, I can remove it soon.

**Comment by ZeroPoke** [comment]
Actually the URLs are bad.  Fixed now.

**Pull request merged**
